fix: bundled monitor content must be idempotent
elastic/synthetics pull request #579
Opened 2022-08-15 22:43 UTC by vigneshshanmugam

+ fix #573 
+ With this change, we effectively removed the date property which was set by the zip stream to always refer to the Unix epoch time instead of defaulting to current time in UTC which was causing the zipped contents to be changed everytime when we run push command.

2022-08-15 22:50 UTC, apmmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Felastic-synthetics%2FPR-579/detail/PR-579/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Felastic-synthetics%2FPR-579/detail/PR-579/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Felastic-synthetics%2FPR-579/detail/PR-579/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Felastic-synthetics%2FPR-579/detail/PR-579/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://synthetics_579.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-08-15T22:33:58.277Z&rangeTo=2022-08-15T22:53:58.277Z&transactionName=BUILD+apm-agent-rum%2Felastic-synthetics%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=fc6f073961757b6efd841af31ec6cce0&transactionId=d219b36881ad0319)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-08-15T22:43:58.277+0000


* Duration: 6 min 7 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Felastic-synthetics%2FPR-579/detail/PR-579/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Checks linting`
<ul>
<li>Took 0 min 4 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-rum/pipelines/elastic-synthetics/pipelines/PR-579/runs/1/steps/184/log/?start=0">here</a></li>
<li>Description: <code>npm run-script lint</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-08-18 17:24 UTC, dominiqueclarke requested changes
Getting a JSON error that doesn't appear in main when pushing to Kibana on main in a directory generated by init. 

<img width="567" alt="Screen Shot 2022-08-18 at 1 23 12 PM" src="https://user-images.githubusercontent.com/11356435/185456886-f1933fb8-7874-4acf-92dc-b95c3e1e98f0.png">

2022-08-18 17:39 UTC, vigneshshanmugam commented
I just rebased on top of main to get the streaming changes. It could be related to that. Can you check it again?

2022-08-18 17:40 UTC, lucasfcosta approved these changes
@dominiqueclarke I think that might be because you're using a version of synthetics which doesn't parse the individual lines of the Kibana output after we changed it to do streaming.

I'll approve this as the changes LGTM. Also, pushes from this branch are okay on my machine, but may be good to wait for @dominiqueclarke to verify on her side as well.

2022-08-18 17:46 UTC, dominiqueclarke commented
> I just rebased on top of main to get the streaming changes. It could be related to that. Can you check it again?

I think it was related to this, will let you know once I get another chance to test.

2022-08-18 18:02 UTC, dominiqueclarke approved these changes
LGTM with main merged! 🚢

2022-08-18 18:22 UTC, merged