fix: use timeout specified in playwright options
elastic/synthetics pull request #663
Opened 2022-11-28 08:31 UTC by shahzad31

We needed this in kibana tests where often timout can increae from 30 seconds, so changing value in each selector is annoying 

fixes  https://github.com/elastic/synthetics/issues/662

2022-11-28 08:32 UTC, shahzad31 commented on examples/todos/basic.journey.ts
> +    await page.goto('https://www.elastic.co/');
```suggestion
    await page.goto(params.url);
```

2022-11-28 08:45 UTC, apmmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Felastic-synthetics%2FPR-663/detail/PR-663/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Felastic-synthetics%2FPR-663/detail/PR-663/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Felastic-synthetics%2FPR-663/detail/PR-663/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Felastic-synthetics%2FPR-663/detail/PR-663/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://synthetics_663.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-11-28T08:21:35.758Z&rangeTo=2022-11-28T08:41:35.758Z&transactionName=BUILD+apm-agent-rum%2Felastic-synthetics%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=1e3fa762805642fda61d73db55da0de5&transactionId=ee19ccfc8b1421f5)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-11-28T08:31:35.758+0000


* Duration: 14 min 14 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 204  |
| Skipped      | 2 |
| Total        | 206   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-11-28 11:07 UTC, emilioalvap commented
IMO, this change could be confusing considering PlaywightOptions type is documenting a different effect, :
```js
 /**
   * Maximum time in milliseconds to wait for the browser instance to start. Defaults to `30000` (30 seconds). Pass `0` to
   * disable timeout.
   */
  timeout?: number;
```

Can we adapt the type object to provide the correct description?

2022-11-28 16:29 UTC, vigneshshanmugam requested changes
Timeout needs to be handled differently. 

Have a read through this issue - [#577 ](https://github.com/elastic/synthetics/issues/561#issuecomment-1215610563)

2022-11-29 09:48 UTC, shahzad31 commented
@vigneshshanmugam isn't it possible to do also global timeout for all selectors. Can you please tell me what would you like me to change for this pr. Instead of using playwrightOptions, adding a new cli param `timeout` will that be ok with you?

2022-11-29 21:56 UTC, vigneshshanmugam commented
Yeah there can be different behavior's for timeout as stated here on the issue - https://github.com/elastic/synthetics/issues/561#issuecomment-1215610563, But if you want to have a monitor with a specified timeout, then go for `--timeout` option. 

But if you are concerned around timeout for PW actions. We cannot do that properly instead users can already do that via
```
journey("test", ({context, browser}) => {
  context.setDefaultTimeout(10000);
})

```

2022-11-30 08:34 UTC, shahzad31 commented
Closing this for now to have more discussions around it

2022-11-30 08:34 UTC, closed without merging