feat: custom transform for bundling and running suites
elastic/synthetics pull request #687
Opened 2022-12-20 22:52 UTC by vigneshshanmugam

### Summary 

There are lot of changes on this PR and needs to be done at the same time so we can get all issues addressed at with sourcemap generation and retrieving them with proper stack trace, Will cover one by one to make it easier for the reviewers

### Running test suites

+ Previously, the agent relied on `ts-node` for transpilation of the journey files which could be written in `.ts, .js or .mjs` files and prior to running the tests, the transformation of these files happens on the fly and resolved internally to the trasnspiled version. This was a good solution for the time being, but turned out to be problematic given the sourcemap locations were wrong most of the times as `ts-node` automatically installs the `source-map-support` module and we will not have granular access to the generated source files. 
+ Now we rely on the custom transformation using `esbuild` to achieve similar behaviour, which means we get the same benefits like automatic transpilation of the TS files, configs, etc. with also granular control of the sourcemap that got generated for those files. This becomes super handy as we can reuse those sourcemaps and maps to those files after bundling using esbuild. 

### Bundling
+ Previously, we used esbuild in Bundling mode with a custom `Synthetics` plugin that resolved all the journey and imported modules without any transpilation and bundled only the external `node_modules`. This was done for main two reasons
   - Reduce the bundle size of the generated journey file - No sourcemaps
   - Replicate the file structure so the errors are captured with proper stacktrace information. 

This method turned our to be really complex and we would need to handle some weird edge cases which is on another PR here - https://github.com/elastic/synthetics/pull/673

+ The current solutions relies on `Esbuild` to bundle the full journey in a single `bundled file` and use sourcemaps that are inlined to map it to the source when errors are thrown. One thing to note here is we set `sourceContents: false` as we dont need the full source content right now as we are not replicating the file structure on the Kibana side, plus removing it also reduces the size by 90%. The rest is just base64 content mappings. 

### Making sourcemaps work
+ To ensure correct sourcemap gets generated during the running suites phase and also post bundling phase, we have to have a single source of truth. Meaning
   - Single tool should be used for transpiling the source journey files and bundling.
   - `source-map-support` should be installed only once, otherwise mapping back to the original source position would become problematic. 
+ We rely on the correct source map also for `journey, step, monitor` functions as we use them to identify all the duplicate monitors and report them as errors. 

Address 
+ fix #652 
+ fix #596

2022-12-20 22:56 UTC, apmmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Felastic-synthetics%2FPR-687/detail/PR-687/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Felastic-synthetics%2FPR-687/detail/PR-687/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Felastic-synthetics%2FPR-687/detail/PR-687/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Felastic-synthetics%2FPR-687/detail/PR-687/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://null_687.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-12-20T22:43:16.773Z&rangeTo=2022-12-20T23:03:16.773Z&transactionName=BUILD+apm-agent-rum%2Felastic-synthetics%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=10337dac44786ebd98c020b37e4a3b79&transactionId=f96a22a35e60d258)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-12-20T22:53:16.773+0000


* Duration: 3 min 54 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Felastic-synthetics%2FPR-687/detail/PR-687/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 9 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-rum/pipelines/elastic-synthetics/pipelines/PR-687/runs/1/steps/10/log/?start=0">here</a></li>
<li>Description: <code>[2022-12-20T22:55:26.714Z] The recommended git tool is: NONE
[2022-12-20T22:55:33.012Z] using crede</code></l1>
</ul>
  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 2 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-rum/pipelines/elastic-synthetics/pipelines/PR-687/runs/1/steps/14/log/?start=0">here</a></li>
<li>Description: <code>[2022-12-20T22:55:45.350Z] The recommended git tool is: NONE
[2022-12-20T22:55:45.361Z] using crede</code></l1>
</ul>
  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 2 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-rum/pipelines/elastic-synthetics/pipelines/PR-687/runs/1/steps/18/log/?start=0">here</a></li>
<li>Description: <code>[2022-12-20T22:55:57.301Z] The recommended git tool is: NONE
[2022-12-20T22:55:57.311Z] using crede</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-01-10 22:38 UTC, andrewvc requested changes
This all looks great, but there's complex implementation details here that could really use comments. The why and how are well fleshed out in the issue description, can you copy that content into the codebase as comments as well?

2023-01-10 22:38 UTC, andrewvc commented on src/push/plugin.ts
> +        // Ignore entry points as these refer to the journey files
love the simplification here

2023-01-17 14:52 UTC, vigneshshanmugam commented on __tests__/push/bundler.test.ts
> +  // avoid dead code elimination
If we dont call utils. Then the code gets eliminated as its unused, which is why I added that comment. Seems like that did not help. I will add more detailed comment in this case.

2023-01-17 14:54 UTC, vigneshshanmugam commented on src/core/transform.ts
> +    minify: false,
Added comments.

2023-01-17 20:26 UTC, andrewvc approved these changes
LGTM

2023-01-17 21:03 UTC, merged