enable use of custom data-test-id
elastic/synthetics pull request #706
Opened 2023-02-22 16:08 UTC by shahzad31

With this we can provide a custom data-test id like `data-test-subj`, will make life easier with kibana tests specifically.

2023-02-22 16:09 UTC, shahzad31 commented on __tests__/core/gatherer.test.ts
> +        '<a target=_blank rel=noopener href="/username-page">popup</a>'
```suggestion
        '<a target=_blank rel=noopener href="/popup.html">popup</a>'
```

2023-02-22 16:22 UTC, apmmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Felastic-synthetics%2FPR-706/detail/PR-706/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Felastic-synthetics%2FPR-706/detail/PR-706/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Felastic-synthetics%2FPR-706/detail/PR-706/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Felastic-synthetics%2FPR-706/detail/PR-706/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://synthetics_706.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2023-02-22T15:58:46.030Z&rangeTo=2023-02-22T16:18:46.030Z&transactionName=BUILD+apm-agent-rum%2Felastic-synthetics%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=72d40dbfe3f917187d4503e0aa7a155e&transactionId=75a52bb0f0f31b2b)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-02-22T16:08:46.030+0000


* Duration: 14 min 50 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 203  |
| Skipped      | 12 |
| Total        | 215   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-02-22 16:25 UTC, vigneshshanmugam reviewed
@shahzad31 Whats the motivation behind this change? I have couple of questions on this

1. why cant Kibana set these attributes on `beforeAll` hook? 
2. Also, since you are doing this on the overall journey, How would it help in the Kibana context since the whole journey could contain multiple elements with these test attributes?

2023-02-22 16:30 UTC, shahzad31 commented
> @shahzad31 Whats the motivation behind this change? I have couple of questions on this
> 
> 1. why cant Kibana set these attributes on `beforeAll` hook?
> 2. Also, since you are doing this on the overall journey, How would it help in the Kibana context since the whole journey could contain multiple elements with these test attributes?

setting it as  `beforeAll` will not work for inline scripts.  Plus we will have to import selectors from playwright-chromium directly. Seems hack to me going outside agent package.

`Also, since you are doing this on the overall journey, How would it help in the Kibana context since the whole journey could contain multiple elements with these test attributes?
`
can you please explain this question?

2023-02-22 16:33 UTC, shahzad31 commented
> @shahzad31 Whats the motivation behind this change? I have couple of questions on this

basic motivation is ability to use `page.getByTestId` selector.

2023-02-22 18:23 UTC, vigneshshanmugam requested changes

2023-02-22 18:23 UTC, vigneshshanmugam commented on __tests__/core/gatherer.test.ts
> +  describe.only('Set Test ID Attribute', () => {
can you remove .only?

2023-02-23 09:06 UTC, shahzad31 commented on __tests__/core/gatherer.test.ts
> +  describe.only('Set Test ID Attribute', () => {
```suggestion
  describe('Set Test ID Attribute', () => {
```

2023-02-23 15:05 UTC, vigneshshanmugam approved these changes
LGTM

2023-02-23 15:05 UTC, merged